from datetime import UTC, datetime
from uuid import UUID, uuid4

from pydantic import EmailStr
from sqlmodel import Field, SQLModel


class BaseIDModel(SQLModel):
    """
    Mixin to add an auto-increment integer primary key to a model.

    This mixin provides an `id` field that serves as the primary key for database tables.
    The ID is automatically generated by the database on insert.

    Attributes:
        id: Auto-incrementing integer primary key. Set to None before insert,
            automatically populated by the database after creation.

    Example:
        ```python
        from sqlmodel import Field, SQLModel
        from fastapi_quickstart.models.mixins import BaseIDModel

        class User(BaseIDModel, table=True):
            name: str = Field(max_length=100)
            email: str = Field(unique=True)
        ```

    API Contract:
        - The `id` field must be None or not set when creating new records
        - After insert, the database assigns a unique integer value
        - The `id` is indexed for fast lookups
        - Compatible with BaseCRUD operations
    """

    id: int | None = Field(
        default=None,
        primary_key=True,
        index=True,
        description="Primary key as an auto-increment integer.",
    )


class BaseUUIDModel(SQLModel):
    """
    Mixin to add a UUID primary key to a model.

    This mixin provides a UUID-based primary key instead of an auto-incrementing integer.
    UUIDs are globally unique and generated before insertion.

    Attributes:
        id: UUID primary key, automatically generated using uuid4() before insert.

    Example:
        ```python
        from sqlmodel import Field, SQLModel
        from fastapi_quickstart.models.mixins import BaseUUIDModel

        class Session(BaseUUIDModel, table=True):
            token: str = Field(max_length=255)
            expires_at: datetime
        ```

    API Contract:
        - The `id` is generated automatically using uuid4() before database insert
        - UUIDs are globally unique across all tables and databases
        - The `id` is indexed for fast lookups
        - Compatible with BaseCRUD operations that accept UUID identifiers
    """

    id: UUID = Field(
        default_factory=uuid4, primary_key=True, index=True, nullable=False, description="Primary key as a UUID."
    )


class SoftDeleteMixin(SQLModel):
    """
    Mixin to add soft delete functionality to a model.

    Soft deletion marks records as deleted without physically removing them from the database.
    This is useful for audit trails, data recovery, and maintaining referential integrity.

    Attributes:
        is_deleted: Boolean flag indicating whether the record is soft-deleted.
            Indexed for efficient filtering of active records.
        deleted_at: Timestamp when the record was soft-deleted. None if not deleted.

    Methods:
        soft_delete(): Mark the record as deleted by setting is_deleted=True
            and deleted_at to current UTC time.
        restore(): Restore a soft-deleted record by setting is_deleted=False
            and deleted_at=None.

    Example:
        ```python
        from sqlmodel import Field, SQLModel
        from fastapi_quickstart.models.mixins import BaseIDModel, SoftDeleteMixin

        class Product(BaseIDModel, SoftDeleteMixin, table=True):
            name: str = Field(max_length=100)
            price: float

        # Using with BaseCRUD
        product = await crud.delete(session, product_id, soft_delete=True)
        ```

    API Contract:
        - By default, is_deleted is False and deleted_at is None
        - When soft-deleting, both fields must be updated together
        - BaseCRUD.delete() supports soft_delete parameter when this mixin is present
        - Queries should filter by is_deleted=False to exclude soft-deleted records
    """

    is_deleted: bool = Field(default=False, index=True, description="Flag indicating if the record is soft deleted.")
    deleted_at: datetime | None = Field(default=None, description="Timestamp when the record was soft deleted.")

    def soft_delete(self) -> None:
        """
        Mark the record as deleted.

        Sets is_deleted=True and deleted_at to the current UTC timestamp.
        Note: This method only updates the model instance; you must commit
        the session to persist changes to the database.
        """
        self.is_deleted = True
        self.deleted_at = datetime.now(UTC)

    def restore(self) -> None:
        """
        Restore the record if it was soft deleted.

        Sets is_deleted=False and deleted_at=None, effectively un-deleting the record.
        Note: This method only updates the model instance; you must commit
        the session to persist changes to the database.
        """
        self.is_deleted = False
        self.deleted_at = None


class TimestampMixin(SQLModel):
    """
    Mixin to add automatic timestamp tracking to a model.

    This mixin adds created_at and updated_at fields that automatically track
    when records are created and last modified. The timestamps use UTC timezone
    for consistency.

    Attributes:
        created_at: Timestamp when the record was first created.
            Automatically set on insert and never updated.
        updated_at: Timestamp when the record was last modified.
            Automatically set on insert and updated on every modification.

    Example:
        ```python
        from sqlmodel import Field, SQLModel
        from fastapi_quickstart.models.mixins import BaseIDModel, TimestampMixin

        class Article(BaseIDModel, TimestampMixin, table=True):
            title: str = Field(max_length=200)
            content: str

        # Timestamps are automatically managed
        article = await crud.create(session, article_data)
        print(article.created_at)  # Set automatically

        article = await crud.update(session, article.id, {"title": "New Title"})
        print(article.updated_at)  # Updated automatically
        ```

    API Contract:
        - created_at is set once on record creation and never modified
        - updated_at is set on creation and updated on every modification
        - Both timestamps use UTC timezone
        - Both fields are non-nullable and always have a value
        - Database automatically updates updated_at on row modifications
    """

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC), nullable=False, description="Timestamp when the record was created."
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        nullable=False,
        sa_column_kwargs={"onupdate": lambda: datetime.now(UTC)},
        description="Timestamp when the record was last updated.",
    )


class BaseUserMixin(SQLModel):
    """
    Mixin to add standard user fields to a model.
    """

    email: EmailStr
    hashed_password: str = Field(nullable=False)
    is_active: bool = Field(default=True, description="Indicates if the user account is active.")
